/**
 * MCP error code registry.
 *
 * **Simple explanation**: A shared list of error labels so everyone speaks the same error language.
 */
export enum ErrorCode {
    INVALID_PARAM = 'INVALID_PARAM',
    TOKEN_LIMIT_EXCEEDED = 'TOKEN_LIMIT_EXCEEDED',
    TIMEOUT = 'TIMEOUT',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    RATE_LIMIT = 'RATE_LIMIT',
    INVALID_STATE = 'INVALID_STATE',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    AUTH_ERROR = 'AUTH_ERROR',
    SCHEMA_VALIDATION_FAILED = 'SCHEMA_VALIDATION_FAILED',
    RECOVERY_TRIGGERED = 'RECOVERY_TRIGGERED',
    BREAKER_FAILED = 'BREAKER_FAILED',
    TOOL_NOT_FOUND = 'TOOL_NOT_FOUND',
    DELEGATION_FAILED = 'DELEGATION_FAILED',
    LOOP_DETECTED = 'LOOP_DETECTED',
    DRIFT_THRESHOLD_EXCEEDED = 'DRIFT_THRESHOLD_EXCEEDED',
    COHERENCE_DROP = 'COHERENCE_DROP',
    TICKET_UPDATE_CONFLICT = 'TICKET_UPDATE_CONFLICT',
    LLM_OFFLINE = 'LLM_OFFLINE',
    LLM_ERROR = 'LLM_ERROR'
}
