// ./researchAgent.Test.ts
import { ResearchAgent } from '../../src/agents/researchAgent.ts';

/** @aiContributed-2026-02-03 */
describe('ResearchAgent', () => {
    /** @aiContributed-2026-02-03 */
    describe('formatReport', () => {
        let researchAgent: ResearchAgent;

        beforeEach(() => {
            researchAgent = new ResearchAgent();
        });

        /** @aiContributed-2026-02-03 */
        it('should format the report correctly with valid query and content', () => {
            const query = 'AI Research';
            const content = 'This is the content of the research.';
            const mockDate = new Date('2023-10-01T12:00:00Z');
            jest.spyOn(global, 'Date').mockImplementation(() => mockDate as unknown as string);

            const result = (researchAgent as unknown as { formatReport: (query: string, content: string) => string }).formatReport(query, content);

            expect(result).toBe(`# Research Report: AI Research

**Generated:** Sunday, October 1, 2023 at 12:00 PM

---

This is the content of the research.

---

*Generated by COE Research Agent*
`);
        });

        /** @aiContributed-2026-02-03 */
        it('should handle empty content gracefully', () => {
            const query = 'AI Research';
            const content = '';
            const mockDate = new Date('2023-10-01T12:00:00Z');
            jest.spyOn(global, 'Date').mockImplementation(() => mockDate as unknown as string);

            const result = (researchAgent as unknown as { formatReport: (query: string, content: string) => string }).formatReport(query, content);

            expect(result).toBe(`# Research Report: AI Research

**Generated:** Sunday, October 1, 2023 at 12:00 PM

---

---

*Generated by COE Research Agent*
`);
        });

        /** @aiContributed-2026-02-03 */
        it('should handle empty query gracefully', () => {
            const query = '';
            const content = 'This is the content of the research.';
            const mockDate = new Date('2023-10-01T12:00:00Z');
            jest.spyOn(global, 'Date').mockImplementation(() => mockDate as unknown as string);

            const result = (researchAgent as unknown as { formatReport: (query: string, content: string) => string }).formatReport(query, content);

            expect(result).toBe(`# Research Report: 

**Generated:** Sunday, October 1, 2023 at 12:00 PM

---

This is the content of the research.

---

*Generated by COE Research Agent*
`);
        });

        /** @aiContributed-2026-02-03 */
        it('should handle both query and content as empty strings', () => {
            const query = '';
            const content = '';
            const mockDate = new Date('2023-10-01T12:00:00Z');
            jest.spyOn(global, 'Date').mockImplementation(() => mockDate as unknown as string);

            const result = (researchAgent as unknown as { formatReport: (query: string, content: string) => string }).formatReport(query, content);

            expect(result).toBe(`# Research Report: 

**Generated:** Sunday, October 1, 2023 at 12:00 PM

---

---

*Generated by COE Research Agent*
`);
        });

        /** @aiContributed-2026-02-03 */
        it('should handle special characters in query and content', () => {
            const query = 'AI & ML Research';
            const content = 'Content with special characters: @#$%^&*()!';
            const mockDate = new Date('2023-10-01T12:00:00Z');
            jest.spyOn(global, 'Date').mockImplementation(() => mockDate as unknown as string);

            const result = (researchAgent as unknown as { formatReport: (query: string, content: string) => string }).formatReport(query, content);

            expect(result).toBe(`# Research Report: AI & ML Research

**Generated:** Sunday, October 1, 2023 at 12:00 PM

---

Content with special characters: @#$%^&*()!

---

*Generated by COE Research Agent*
`);
        });

        afterEach(() => {
            jest.restoreAllMocks();
        });
    });
});